var messages = {
	/**
	 * common
	 */
	"yly.common.createDate" : "创建时间",
	"yly.common.modifyDate" : "修改时间",
	"yly.common.title" : "标题",
	"yly.common.loading" : "加载中...",
	"yly.common.save" : "保存",
	"yly.common.saving" : "保存中...",
	"yly.common.add" : "添加",
	"yly.common.edit" : "编辑",
	"yly.common.remove" : "删除",
	"yly.common.cancel" : "取消",
    "yly.common.close" : "关闭",
	"yly.common.progress" : "正在处理中...",
	"yly.common.prompt" : "操作提示",
	"yly.common.success" : "操作成功",
	"yly.common.fail" : "操作失败",
	"yly.common.unknow.error" : "未知错误",
	"yly.common.select.editRow" : "请选择要编辑的记录",
	"yly.common.select.editRow.unique" : "只能选择一条记录修改",
	"yly.common.select.deleteRow" : "请选择要删除的内容",
	"yly.common.confirm" : "确认",
	"yly.common.delete.confirm" : "您确认想要删除记录吗？",
	"yly.common.gender": "性别",
	"yly.common.name":"姓名",
	"yly.common.age":"年龄",
	"yly.common.birthday":"出生日期",
	"yly.common.relation":"与老人关系",
	"yly.common.infoChannel":"信息来源",
	"yly.common.remark":"备注",
	"yly.common.phonenumber":"电话号码",
	"yly.common.male":"男",
	"yly.common.female":"女",
	"yly.common.other":"其它",
	"yly.common.yes":"是",
	"yly.common.no":"否",
	"yly.common.detail":"详情",
	"yly.common.relation.self":"本人",
	"yly.common.relation.children":"子女",
	"yly.common.relation.marriage_relationship":"夫妻",
	"yly.common.relation.grandparents_and_grandchildren":"祖孙",
	"yly.common.relation.brothers_or_sisters":"兄弟或姐妹",
	"yly.common.relation.daughterinlaw_or_soninlaw":"儿媳或女婿",
	"yly.common.relation.friend":"朋友",
	"yly.common.relation.infochannel.network":"网络",
	"yly.common.relation.infochannel.community":"社区",
	"yly.common.relation.infochannel.ohter_introduct":"他人介绍",
	"yly.common.relation.infochannel.advertisement":"广告",
	"yly.common.idcard":"身份证号码",
	"yly.common.disable":"禁用",
	"yly.common.enable":"启用",
	"yly.common.elderlyname":"老人姓名",
	"yly.common.bedRoom":"房间",
	"yly.common.nurseLevel":"护理等级",
	"yly.common.please.select":"请选择...",
	"yly.common.insertDate": "录入时间",
	"yly.common.notice":"注意",
	
	
	/**
	 * charge manage
	 */
	"yly.charge.status.paid" : "已缴费",
	"yly.charge.status.unpaid" : "未缴费",
	"yly.charge.status.unpaid_adjustment" : "未缴费(调账)",
	"yly.charge.status.refunded" : "已退款",
	"yly.deposit.charge.record" : "押金",
	"yly.advance.charge.record" : "预存款",
	"yly.charge.advance" : "预存款(元)",
	"yly.charge.checkin" : "入院收费",
	"yly.pay.checkin" : "入院缴费",
	"yly.charge.checkout" : "退住结算",
	"yly.bedNurse.charge.record" : "床位护理费",
	"yly.meal.charge.record" : "伙食费",
	"yly.waterElectricity.charge.record" : "水电费",
	"yly.service.charge.record" : "个性化服务费",
	"yly.charge.record.depositAmount":"押金(元)",
	"yly.charge.record.invoiceNo" : "收据票号",
	"yly.charge.record.bed" : "床位费(元)",
	"yly.charge.record.nurse" : "护理费(元)",
	"yly.charge.record.totalAmount" : "总金额(元)",
	"yly.charge.record.advanceChargeAmount" : "预存款总额(元)",
	"yly.charge.record.operator" : "经办人",
	"yly.charge.record.payStaff" : "收款人",
	"yly.charge.record.period" : "收款时间段",
	"yly.charge.record.payTime" : "缴费时间",
	"yly.charge.record.oprTime" : "办理时间",
	"yly.charge.record.calTime" : "结算时间",
	"yly.charge.record.status" : "状态",
	"yly.charge.record.meal" : "伙食费(元)",
	"yly.charge.record.meal.type" : "伙食类型",
	"yly.charge.record.service" : "服务费(元)",
	"yly.charge.record.water" : "水费(元)",
	"yly.charge.record.electricity" : "电费(元)",
	"yly.charge.record.water.count" : "水用量(吨)",
	"yly.charge.record.electricity.count" : "电用量(度)",
	"yly.charge.record.amount" : "金额(元)",
	"yly.charge.record.budgetType" : "收支类型",
	"yly.charge.record.budgetType.income" : "充值",
	"yly.charge.record.budgetType.cost" : "消费",
	"yly.charge.advance.add" : "预缴款",
	"yly.charge.record.list":"缴费列表",
	"yly.charge.checkout.list":"结算列表",
	"yly.charge.record.perMonth":"月收费: ￥",	
	"yly.charge.record.perDay":"日收费: ￥",
	"yly.charge.billing.day.prefix":"每月",
	"yly.charge.billing.day.suffix":"号为账单结算日期",
	"yly.charge.billing.prompt.already.paid":"该老人已经缴费！",
	"yly.charge.billing.confirm.paid.adjust":"账单已缴费，您确定要进行调账?",
	"yly.charge.billing.adjust":"调整金额",
	"yly.charge.billing.edit":"修改账单",
	
	
	
	
	/**
	 * charge config
	 */
	"yly.nurse.charge.config" : "护理费费配置",
	"yly.meal.charge.config" : "伙食费配置",
	"yly.waterElectricity.charge.config" : "水电费配置",
	"yly.bed.charge.config" : "床位费配置",
	"yly.service.charge.config" : "服务费配置",
	"yly.charge.amount.day" : "金额(元)/天",
	"yly.charge.amount.month" : "金额(元)/月",
	"yly.charge.amount.times" : "金额(元)/次",
	// bedChargeConfig
	"yly.bedCharge.bedType" : "床位类型",
	"yly.bedCharge.add" : "添加床位费配置",
	"yly.bedCharge.edit" : "编辑床位费配置",
	// nurseChargeConfig
	"yly.nurseCharge.nurseLevel" : "护理级别",
	"yly.nurseCharge.add" : "添加护理费配置",
	"yly.nurseCharge.edit" : "编辑护理费配置",
	//mealCharegeConfig
	"yly.mealCharge.mealType" : "伙食类型",
	"yly.mealCharge.add" : "添加伙食费配置",
	"yly.mealCharge.edit" : "编辑伙食费配置",
	//waterElectricityChargeConfig
	"yly.charge.water.amount" : "水(元/吨)",
	"yly.charge.electricity.amount" : "电(元/度)",
	"yly.waterElectricityCharge.add" : "添加水电费配置",
	"yly.waterElectricityCharge.edit" : "编辑水电费配置",
	//personalizedChargeConfig
	"yly.personalizedCharge.item" : "服务项目",
	"yly.personalizedCharge.add" : "添加服务费配置",
	"yly.personalizedCharge.edit" : "编辑服务费配置",
	//consultation
	"yly.consultation.record":"咨询记录",
	"yly.consultation.vistor":"咨询人",
	"yly.consultation.checkinintention":"入住意向",
	"yly.consultation.returnVisit":"是否回访",
	"yly.consultation.returnVisitDate":"回访时间",
	"yly.consultation.elderlyHealth":"健康状况",
	"yly.consultation.add":"添加咨询",
	"yly.consultation.checkinIntention.confirmed":"确认入住",
	"yly.consultation.checkinIntention.will_to_checkin_strongly":"入住意愿强",
	"yly.consultation.checkinIntention.will_to_checkin_not_strongly":"入住意愿不强",
	"yly.consultation.checkinIntention.will_not_checkin":"不入住",
	
	//visitelderly
	"yly.visitelderly.add":"添加探望",
	"yly.visitelderly.record":"探望记录",
	"yly.visitelderly.elderlyInfo":"被探望老人",
	"yly.visitelderly.visitor":"来访者",
	"yly.visitelderly.visitPersonnelNumber":"来访人数",
	"yly.visitelderly.visitDate":"来访时间",
	"yly.visitelderly.dueLeaveDate":"预计离开时间",
	"yly.visitelderly.reasonForVisit":"来访原因",
	"yly.visitelderly.search":"老人查询",
	
	//bookingRegistration
	"yly.bookingRegistration.record":"预约记录",
	"yly.bookingRegistration.peopleWhoBooked":"预约人",
	"yly.bookingRegistration.bookingCheckInDate":"预约入住时间",
	"yly.bookingRegistration.add":"添加预约",
	"yly.bookingRegistration.intentRoomType":"意向房型",
	// volunteer
	"yly.volunteer.record":"志愿者记录",
	"yly.volunteer.name":"志愿者姓名",
	"yly.volunteer.type":"类型",
	"yly.volunteer.idCard":"证件号",
	"yly.volunteer.email":"邮件",
	"yly.volunteer.address":"地址",
	"yly.volunteer.zipCode":"邮编",
	"yly.volunteer.telephone":"电话",
	"yly.volunteer.mobile":"手机",
	"yly.volunteer.add":"添加志愿者",
	"yly.volunteer.personal":"个人",
	"yly.volunteer.organization":"组织机构",
	"yly.volunteer.activityTime":"活动时间",
	
	//elderlyinfo
	"yly.admission.add":"办理入院",
	"yly.elderlyinfo":"老人信息",
	"yly.elderly.status":"老人状态",
	"yly.elderly.status.in_nursing_home":"在院",
	"yly.elderly.status.out_nursing_home":"出院",
	"yly.elderly.status.in_progress_checkin":"入院办理",
	"yly.elderly.status.in_progress_checkout":"出院办理",
	"yly.elderly.status.dead":"过世",
	"yly.elderlyinfo.identifier":"编号",
	"yly.elderlyinfo.bed":"床位",
	"yly.elderlyinfo.record":"老人信息",
	"yly.elderlyInfo.identifier":"老人编号",
	"yly.elderlyInfo.photo":"照片",
	"yly.elderlyInfo.placeOfOrigin":"籍贯",
	"yly.elderlyInfo.nation":"籍贯",
	"yly.elderlyInfo.birthday":"出生日期",
	"yly.elderlyInfo.socialInsuranceNumber":"出生日期",
	"yly.elderlyInfo.evaluatingResult":"评估结果",
	"yly.elderlyInfo.evaluatingScore":"评估分数",
	"yly.elderlyInfo.bed":"床位",
	"yly.elderlyInfo.elderlyPhoneNumber":"老人电话",
	"yly.elderlyInfo.personnelCategory":"人员类别",
	"yly.elderlyInfo.registeredResidence":"户口地址",
	"yly.elderlyInfo.residentialAddress":"现居地址",
	"yly.elderlyInfo.originalCompany":"原工作单位",
	"yly.elderlyInfo.position":"原职位",
	"yly.elderlyInfo.honors":"曾获荣誉",
	"yly.elderlyInfo.hobbies":"爱好",
	"yly.elderlyInfo.personalHabits":"个人习惯",
	"yly.elderlyInfo.paymentWay":"费用支付方式",
	"yly.elderlyInfo.nursingLevel":"护理级别",
	"yly.elderlyInfo.educationLevel":"文化程度",
	"yly.elderlyInfo.politicalOutlook":"政治面貌",
	"yly.elderlyInfo.religion":"宗教",
	"yly.elderlyInfo.marriageState":"婚姻状况",
	"yly.elderlyInfo.beHospitalizedDate":"入院时间",
	"yly.elderlyInfo.livingState":"居住情况",
	"yly.elderlyInfo.housingInfo":"住房信息",
	"yly.elderlyInfo.medicalExpPaymentWay":"医疗支付方式",
	"yly.elderlyInfo.monthlyIncome":"月收入",
	"yly.elderlyInfo.sourceOfIncome":"收入来源",
	"yly.elderlyInfo.elderlyConsigner":"委托人",
	"yly.elderlyInfo.elderlyConsigner.consignerPhoneNumber":"委托人电话",
	"yly.elderlyInfo.elderlyFamilyMembers":"家庭成员",

		
	//床位管理
	"yly.bulding.add":"添加楼宇",
	"yly.bulding.edit":"楼宇编辑",
	"yly.bulding.list":"楼宇列表",
	"yly.bulding.buildingName":"楼宇名称",
	"yly.bulding.description":"描述",
	"yly.room.add":"房间添加",
	"yly.room.edit":"房间编辑",
	"yly.room.list":"房间列表",
	"yly.room.roomName":"房间名称",
	"yly.room.roomNumber":"房间编号",
	"yly.room.floor":"房间所在楼层",
	"yly.room.roomType":"房间类型",
	"yly.room.roomStatus":"房间状态",
	"yly.room.building":"所属楼宇",
	"yly.room.description":"房间描述",
	"yly.bed.add":"床位添加",
	"yly.bed.edit":"床位编辑",
	"yly.bed.list":"床位列表",
	"yly.bed.bedNumber":"床位号",
	"yly.bed.status":"床位状态",
	"yly.bed.description":"描述",
	"yly.bed.room":"所在房间",
	"yly.common.unappropriated":"未占用",
	"yly.common.occupied":"已占用",
	"yly.bed.usageState":"是否被占用",
	//黑名单
	"yly.blacklist.record":"黑名单",
	"yly.blacklist.name":"黑名单老人名字",
	"yly.blacklist.geracomium":"所属养老院",
	"yly.blacklist.casue":"加入黑名单原因",
	"yly.blacklist.add":"加入黑名单",		
		
	//老人管理
	"yly.elderlyInfo.common.operator":"记录人",
	"yly.elderlyInfo.event.eventDate":"事件发生时间",
	"yly.elderlyInfo.event.content":"事件内容",
	"yly.elderlyInfo.event.list":"事件列表",
    "yly.elderly.event.add":"添加事件",
    "yly.elderly.event.edit":"编辑事件",
    "yly.elderlyInfo.stuffDeposit.list":"物品寄存列表",
    "yly.elderly.stuffDeposit.add":"添加物品寄存",
    "yly.elderly.stuffDeposit.edit":"编辑物品寄存",
    "yly.elderly.Photo.Album":"相册名称",
    "yly.elderly.Photo.Album.view":"浏览图片",
    "yly.elderly.Photo.Album.add":"添加相册照片",
	//物品寄存
    "yly.elderlyInfo.stuffDeposit.name":"物品名称",	
    "yly.elderlyInfo.stuffDeposit.count":"数量",
    "yly.elderlyInfo.stuffDeposit.remark":"物品备注",
    "yly.elderlyInfo.stuffDeposit.stuffNumer":"物品编号",
    "yly.elderlyInfo.stuffDeposit.status":"寄存状态",
    "yly.elderlyInfo.stuffDeposit.inputDate":"寄存时间",
    "yly.elderlyInfo.stuffDeposit.takeAwayDate":"取出时间",	
    "yly.elderlyInfo.stuffDeposit.elderlyName":"所属老人",
    "yly.elderlyInfo.stuffDeposit.putin":"存入",
    "yly.elderlyInfo.stuffDeposit.takeaway":"取走",
    //维修人员
    "yly.repairRecord.add":"添加维修记录",
	"yly.repairRecord.record":"维修记录",
	"yly.repairRecord.repairContent":"维修内容",
	"yly.repairRecord.repairPlace":"维修地点",
	"yly.repairRecord.reportOperator":"报修人",
	"yly.repairRecord.repairOperator":"维修人员",
	
	//水电用量记录
	"yly.waterElectricityRecord.add":"水电用量记录添加",
	"yly.waterElectricityRecord.record":"水电用量列表",
	"yly.waterElectricityRecord.waterActual":"用水计费吨数",
	"yly.waterElectricityRecord.electricityActual":"用电计费度数",
	"yly.waterElectricityRecord.operator":"抄表人",
	
	//药品管理
	"yly.drugsInfo.list":"药品列表",
	"yly.drugsInfo.add":"药品添加",
	"yly.drugsInfo.name":"药品名称",
	"yly.drugsInfo.alias":"别名",
	"yly.drugsInfo.drugCategory":"药品分类",
	
	//捐赠管理
	"yly.donateRecord.list":"捐赠记录",
	"yly.donateRecord.add":"添加捐赠记录",
	"yly.donateRecord.donatorName":"捐赠记录",
	"yly.donateRecord.donatorPhone":"捐赠人电话",
	"yly.donateRecord.donateTime":"捐赠时间",
	"yly.donateDetail.donateAmount":"捐赠数",
	"yly.donateDetail.donateType":"捐赠类型",
	"yly.donateDetail.donateType.money":"钱",
	"yly.donateDetail.donateType.item":"物",
	"yly.donateDetail.donateItemType":"捐赠物品类型",
	"yly.donateDetail.add":"添加捐赠详情",
	//固定资产
	"yly.fixedAssets.list":"固定资产列表",
	"yly.fixedAssets.assetNo":"资产编号",
	"yly.fixedAssets.assetName":"资产名称",
	"yly.fixedAssets.department":"存放部门",
	"yly.fixedAssets.assetCount":"资产数量",
	"yly.fixedAssets.assetTime":"录入时间",
	//租户用户
	"yly.tenantUser.list":"用户列表",
	"yly.tenantUser.realName":"姓名",
	"yly.tenantUser.gender":"性别",
	"yly.tenantUser.age":"年龄",
	"yly.tenantUser.staffID":"员工编号",
	"yly.tenantUser.staffStatus":"员工状态",
	"yly.tenantUser.staffStatus.inService":"在职",
	"yly.tenantUser.staffStatus.outService":"离职",
	"yly.tenantUser.department":"所在部门",
	"yly.tenantUser.position":"担任职务",
	"yly.tenantUser.hireDate":"入职时间",
	
	//department
	"yly.department.name":"部门名称",
	"yly.department.grade":"部门层级",
	"yly.department.parent":"上级部门",
	"yly.department.add":"添加部门",
	
	//position
	"yly.position.add":"添加职位",
	"yly.position.name":"职位名称",
	"yly.position.department":"隶属部门",

	//权限管理
	"yly.role.record":"角色管理",
	"yly.role.name":"角色名称",
	"yly.role.description":"描述",
	"yly.role.add":"添加角色",
	"yly.role.auth":"授权",
	"yly.role.auth.manange":"权限分配",
	"yly.role.auth.name":"菜单名称",
	"yly.role.auth.status":"权限状态",
	"yly.drugsInfo.doseFrequency.Qd":"一天一次(Qd)",
	"yly.drugsInfo.doseFrequency.Bid":"一天两次(Bid)",
	"yly.drugsInfo.doseFrequency.Tid":"一天三次(Tid)",
	"yly.drugsInfo.doseFrequency.Qid":"一天四次(Qid)",
	"yly.drugsInfo.doseFrequency.Q2h":"两小时一次(Q2h)",
	"yly.drugsInfo.doseFrequency.Q4h":"四小时一次(Q4h)",
	//病历管理
	"yly.medicalRecord.list":"病历列表",
	"yly.medicalRecord.add":"添加病历",
	//通知公告
	"yly.notification.operator":"发布人",
	"yly.notification.publishTime":"发布时间",
	"yly.notification.list":"通知列表",
	"yly.notification.add":"添加通知公告"
};
//多语言
function message(code) {
	if (code != null) {
		var content = messages[code] != null ? messages[code] : code;
		if (arguments.length == 1) {
			return content;
		} else {
			if ($.isArray(arguments[1])) {
				$.each(arguments[1], function(i, n) {
					content = content.replace(
							new RegExp("\\{" + i + "\\}", "g"), n);
				});
				return content;
			} else {
				$.each(Array.prototype.slice.apply(arguments).slice(1),
						function(i, n) {
							content = content.replace(new RegExp("\\{" + i
									+ "\\}", "g"), n);
						});
				return content;
			}
		}
	}
}
