var messages = {
	/**
	 * common
	 */
	"yly.common.createDate" : "创建时间",
	"yly.common.modifyDate" : "修改时间",
	"yly.common.title" : "标题",
	"yly.common.loading" : "加载中...",
	"yly.common.save" : "保存",
	"yly.common.saving" : "保存中...",
	"yly.common.add" : "添加",
	"yly.common.edit" : "编辑",
	"yly.common.remove" : "删除",
	"yly.common.cancel" : "取消",
    "yly.common.close" : "关闭",
	"yly.common.progress" : "正在处理中...",
	"yly.common.prompt" : "操作提示",
	"yly.common.success" : "操作成功",
	"yly.common.fail" : "操作失败",
	"yly.common.unknow.error" : "未知错误",
	"yly.common.select.editRow" : "请选择要编辑的记录",
	"yly.common.select.editRow.unique" : "只能选择一条记录修改",
	"yly.common.select.deleteRow" : "请选择要删除的内容",
	"yly.common.confirm" : "确认",
	"yly.common.delete.confirm" : "您确认想要删除记录吗？",
	"yly.common.gender": "性别",
	"yly.common.name":"姓名",
	"yly.common.age":"年龄",
	"yly.common.birthday":"出生日期",
	"yly.common.relation":"与老人关系",
	"yly.common.infoChannel":"信息来源",
	"yly.common.remark":"备注",
	"yly.common.phonenumber":"电话号码",
	"yly.common.male":"男",
	"yly.common.female":"女",
	"yly.common.other":"其它",
	"yly.common.yes":"是",
	"yly.common.no":"否",
	"yly.common.detail":"详情",
	"yly.common.relation.self":"本人",
	"yly.common.relation.children":"子女",
	"yly.common.relation.marriage_relationship":"夫妻",
	"yly.common.relation.grandparents_and_grandchildren":"祖孙",
	"yly.common.relation.brothers_or_sisters":"兄弟或姐妹",
	"yly.common.relation.daughterinlaw_or_soninlaw":"儿媳或女婿",
	"yly.common.relation.friend":"朋友",
	"yly.common.relation.infochannel.network":"网络",
	"yly.common.relation.infochannel.community":"社区",
	"yly.common.relation.infochannel.ohter_introduct":"他人介绍",
	"yly.common.relation.infochannel.advertisement":"广告",
	"yly.common.idcard":"身份证号码",
	"yly.common.disable":"禁用",
	"yly.common.enable":"启用",
	"yly.common.elderlyname":"老人姓名",
	"yly.common.bedRoom":"房间",
	"yly.common.nurseLevel":"护理等级",
	"yly.common.please.select":"请选择...",
	"yly.common.insertDate": "录入时间",
	"yly.common.notice":"注意",
	"yly.common.notice.current_condition_no_export_data":"当前条件无可导出的数据。",
	"yly.common.notice.comfirm_export_data":"确定导出 {0} 条记录？",
	"yly.common.notice.export_data_too_much_advice_use_filter":"导出数据超过 {0} 条数据，建议搜索查询条件以缩小查询范围，再导出。",
	"yly.common.notice.need_wait_export_too_much_data":"导出共有 {0} 条数据，导出超过 {1} 条数据可能需要您耐心等待，仍需操作请确定继续。",
	"yly.common.address":"地址",
	"yly.common.print":"打印",
	"yly.common.action":"操作",
	"yly.common.dateFormatChina":"yyyy年MM月dd日",
	"yly.common.elderlyInfo":"老人基本信息",
	
	/**
	 * charge manage
	 */
	"yly.charge.advancePay.unavaliable" : "预存款不足，请选择其它支付方式",
	"yly.charge.status.paid" : "已缴费",
	"yly.charge.status.unpaid" : "未缴费",
	"yly.charge.status.unpaid_adjustment" : "未缴费(调账)",
	"yly.charge.status.refunded" : "已退款",
	"yly.deposit.charge.record" : "押金",
	"yly.advance.charge.record" : "预存款",
	"yly.charge.advance" : "预存款(元)",
	"yly.charge.checkin" : "入院收费",
	"yly.pay.checkin" : "入院缴费",
	"yly.pay.dailyBill" : "日常缴费",
	"yly.charge.checkoutPay" : "退住结算",
	"yly.bedNurse.charge.record" : "床位护理费",
	"yly.meal.charge.record" : "伙食费",
	"yly.waterElectricity.charge.record" : "水电费",
	"yly.service.charge.record" : "个性化服务费",
	"yly.charge.record.depositAmount":"押金(元)",
	"yly.charge.record.invoiceNo" : "收据票号",
	"yly.charge.record.bed" : "床位费(元)",
	"yly.charge.record.nurse" : "护理费(元)",
	"yly.charge.record.totalAmount" : "总金额(元)",
	"yly.charge.record.advanceChargeAmount" : "预存款总额(元)",
	"yly.charge.record.operator" : "经办人",
	"yly.charge.record.payStaff" : "收款人",
	"yly.charge.record.period" : "收款时间段",
	"yly.charge.record.payTime" : "缴费时间",
	"yly.charge.record.oprTime" : "办理时间",
	"yly.charge.record.calTime" : "结算时间",
	"yly.charge.record.status" : "状态",
	"yly.charge.record.meal" : "伙食费(元)",
	"yly.charge.record.meal.type" : "伙食类型",
	"yly.charge.record.service" : "服务费(元)",
	"yly.charge.record.water" : "水费(元)",
	"yly.charge.record.electricity" : "电费(元)",
	"yly.charge.record.water.count" : "水用量(吨)",
	"yly.charge.record.electricity.count" : "电用量(度)",
	"yly.charge.record.amount" : "金额(元)",
	"yly.charge.record.budgetType" : "收支类型",
	"yly.charge.record.budgetType.income" : "充值",
	"yly.charge.record.budgetType.cost" : "消费",
	"yly.charge.advance.add" : "预缴款",
	"yly.charge.record.list":"缴费列表",
	"yly.charge.checkoutPay.list":"结算列表",
	"yly.charge.record.perMonth":"月收费: ￥",	
	"yly.charge.record.perDay":"日收费: ￥",
	"yly.charge.billing.day.prefix":"每月",
	"yly.charge.billing.day.suffix":"号为账单结算日期",
	"yly.charge.billing.prompt.already.paid":"该老人已经缴费！",
	"yly.charge.billing.confirm.paid.adjust":"账单已缴费，您确定要进行调账?",
	"yly.charge.billing.adjust":"调整金额",
	"yly.charge.billing.edit":"修改账单",
	"yly.chargein.billing.isUpdated":"该账单缴费后已修改过，不允许再次修改!",
	"yly.checkout.charge.depositInfo":"押金： ￥ {0}  ({1})\n",
	"yly.checkout.charge.bedAmountInfo":"床位费： ￥ {0}  ({1})\n",
	"yly.checkout.charge.nurseAmountInfo":"护理费： ￥ {0}  ({1}) \n",
	"yly.checkout.charge.mealAmountInfo":"伙食费： ￥ {0}  ({1}) \n",
	"yly.checkout.charge.waterAmountInfo":"水费： ￥ {0}  ({1}) \n",
	"yly.checkout.charge.electricityAmountInfo":"电费： ￥ {0}  ({1}) \n",
	"yly.checkout.charge.personalizedAmountInfo":"个性化服务费： ￥ {0}  ({1}) \n",
	"yly.checkout.charge.remarkInfo":"(备注：{0} ) \n",
	"yly.checkout.charge.DateFromTo":"{0} 至 {1} ",
	"yly.checkout.charge.null":"无",		
	"yly.charge.PAID":"已缴费",
	"yly.charge.UNPAID":"未缴费",
	"yly.charge.UNPAID_ADJUSTMENT":"未缴费(调账)",
	"yly.charge.REFUNDED":"已退款",   
	"yly.checkout.charge.refundDeposit":"需要退押金",
	"yly.checkout.charge.noDeposit":"无押金",
	"yly.checkout.charge.no_billing":"该用户没有结算账单！",
	"yly.checkout.keyin_checkout_date":"请先确定出院日期！",
	"yly.checkout.confirm_checkoutCharge_for_elderly":"确认要给老人 {0}  办理出院？ ",
	"yly.checkout.confirm_checkoutPay_for_elderly":" {0}  办理退住结算，共缴费￥：{1}  ",
	"yly.checkout.dialog.title":"办理退住结算",
	"yly.checkout.confirm_paymentType_amount":"请选择支付方式并核对金额！",
	"yly.checkout.elderlyStatus.invalid":"非法操作，老人 {0} 已经出院或者已将办理出院了，不能再次办理出院！",
	"yly.checkout.elderlyStatus.invalid.adjustment":"非法操作，老人 {0} 已经出院，不能进行调账！",
	"yly.charge.billing.adjustment":"调整金额",
	"yly.charge.billing.adjustment.cause":"调账原因",
	"yly.charge.billing.adjustment.amount":"调账金额",
	"yly.bedNurse.charge.label" : "床位护理费：￥ {0}",
	"yly.meal.charge.label" : "伙食费：￥ {0}",
	"yly.waterElectricity.charge.label" : "水电费：￥ {0}",
	"yly.personalized.charge.label" : "个性化服务费：￥ {0}",
	"yly.deposit.charge.label":"押金：￥ {0}",
	"yly.waterElectricity.remark.label":"截止到办理出院，欠水（吨）：{0} \t [单价 ￥ {1}/ 吨] \t 水费小计：￥{2}\n截止到办理出院，欠电（度）：{3} \t [单价 ￥ {4}/ 度] \t 电费小计：￥{5}\n",
	"yly.checkout.outHospitalizedDate":"出院日期: ",
	"yly.checkout.charge":"办理出院",
	"yly.charge.billing.status":"账单状态",
	
	/**
	 * charge config
	 */
	"yly.nurse.charge.config" : "护理费费配置",
	"yly.meal.charge.config" : "伙食费配置",
	"yly.waterElectricity.charge.config" : "水电费配置",
	"yly.bed.charge.config" : "床位费配置",
	"yly.service.charge.config" : "服务费配置",
	"yly.charge.amount.day" : "金额(元)/天",
	"yly.charge.amount.month" : "金额(元)/月",
	"yly.charge.amount.times" : "金额(元)/次",
	// bedChargeConfig
	"yly.bedCharge.bedType" : "床位类型",
	"yly.bedCharge.add" : "添加床位费配置",
	"yly.bedCharge.edit" : "编辑床位费配置",
	// nurseChargeConfig
	"yly.nurseCharge.nurseLevel" : "护理级别",
	"yly.nurseCharge.add" : "添加护理费配置",
	"yly.nurseCharge.edit" : "编辑护理费配置",
	//mealCharegeConfig
	"yly.mealCharge.mealType" : "伙食类型",
	"yly.mealCharge.add" : "添加伙食费配置",
	"yly.mealCharge.edit" : "编辑伙食费配置",
	//waterElectricityChargeConfig
	"yly.charge.water.amount" : "水(元/吨)",
	"yly.charge.electricity.amount" : "电(元/度)",
	"yly.waterElectricityCharge.add" : "添加水电费配置",
	"yly.waterElectricityCharge.edit" : "编辑水电费配置",
	//personalizedChargeConfig
	"yly.personalizedCharge.item" : "服务项目",
	"yly.personalizedCharge.add" : "添加服务费配置",
	"yly.personalizedCharge.edit" : "编辑服务费配置",
	//consultation
	"yly.consultation.record":"咨询记录",
	"yly.consultation.vistor":"咨询人",
	"yly.consultation.checkinintention":"入住意向",
	"yly.consultation.returnVisit":"是否回访",
	"yly.consultation.returnVisitDate":"回访时间",
	"yly.consultation.elderlyHealth":"健康状况",
	"yly.consultation.add":"添加咨询",
	"yly.consultation.checkinIntention.confirmed":"确认入住",
	"yly.consultation.checkinIntention.will_to_checkin_strongly":"入住意愿强",
	"yly.consultation.checkinIntention.will_to_checkin_not_strongly":"入住意愿不强",
	"yly.consultation.checkinIntention.will_not_checkin":"不入住",
	
	//visitelderly
	"yly.visitelderly.add":"添加探望",
	"yly.visitelderly.record":"探望记录",
	"yly.visitelderly.elderlyInfo":"被探望老人",
	"yly.visitelderly.visitor":"来访者",
	"yly.visitelderly.visitPersonnelNumber":"来访人数",
	"yly.visitelderly.visitDate":"来访时间",
	"yly.visitelderly.dueLeaveDate":"预计离开时间",
	"yly.visitelderly.reasonForVisit":"来访原因",
	"yly.visitelderly.search":"老人查询",
	
	//bookingRegistration
	"yly.bookingRegistration.record":"预约记录",
	"yly.bookingRegistration.peopleWhoBooked":"预约人",
	"yly.bookingRegistration.bookingCheckInDate":"预约入住时间",
	"yly.bookingRegistration.add":"添加预约",
	"yly.bookingRegistration.intentRoomType":"意向房型",
	// volunteer
	"yly.volunteer.record":"志愿者记录",
	"yly.volunteer.name":"志愿者姓名",
	"yly.volunteer.type":"类型",
	"yly.volunteer.idCard":"证件号",
	"yly.volunteer.email":"邮件",
	"yly.volunteer.address":"地址",
	"yly.volunteer.zipCode":"邮编",
	"yly.volunteer.telephone":"电话",
	"yly.volunteer.mobile":"手机",
	"yly.volunteer.add":"添加志愿者",
	"yly.volunteer.personal":"个人",
	"yly.volunteer.organization":"组织机构",
	"yly.volunteer.activityTime":"活动时间",
	
	//elderlyinfo
	"yly.admission.add":"办理入院",
	"yly.addmission.bed.search":"床位查询",
	"yly.elderlyinfo":"老人信息",
	"yly.elderly.status":"老人状态",
	"yly.elderly.status.in_nursing_home":"在院",
	"yly.elderly.status.out_nursing_home":"出院",
	"yly.elderly.status.in_progress_checkin":"入院办理",
	"yly.elderly.status.in_progress_checkout":"出院办理",
	"yly.elderly.status.dead":"过世",
	"yly.elderlyinfo.identifier":"编号",
	"yly.elderlyinfo.bed":"床位",
	"yly.elderlyinfo.record":"老人信息",
	"yly.elderlyInfo.identifier":"老人编号",
	"yly.elderlyInfo.photo":"照片",
	"yly.elderlyInfo.placeOfOrigin":"籍贯",
	"yly.elderlyInfo.nation":"籍贯",
	"yly.elderlyInfo.birthday":"出生日期",
	"yly.elderlyInfo.socialInsuranceNumber":"出生日期",
	"yly.elderlyInfo.evaluatingResult":"评估结果",
	"yly.elderlyInfo.evaluatingScore":"评估分数",
	"yly.elderlyInfo.bed":"床位",
	"yly.elderlyInfo.elderlyPhoneNumber":"老人电话",
	"yly.elderlyInfo.personnelCategory":"人员类别",
	"yly.elderlyInfo.registeredResidence":"户口地址",
	"yly.elderlyInfo.residentialAddress":"现居地址",
	"yly.elderlyInfo.originalCompany":"原工作单位",
	"yly.elderlyInfo.position":"原职位",
	"yly.elderlyInfo.honors":"曾获荣誉",
	"yly.elderlyInfo.hobbies":"爱好",
	"yly.elderlyInfo.personalHabits":"个人习惯",
	"yly.elderlyInfo.paymentWay":"费用支付方式",
	"yly.elderlyInfo.nursingLevel":"护理级别",
	"yly.elderlyInfo.educationLevel":"文化程度",
	"yly.elderlyInfo.politicalOutlook":"政治面貌",
	"yly.elderlyInfo.religion":"宗教",
	"yly.elderlyInfo.marriageState":"婚姻状况",
	"yly.elderlyInfo.beHospitalizedDate":"入院时间",
	"yly.elderlyInfo.outHospitalizedDate":"出院时间",
	"yly.elderlyInfo.livingState":"居住情况",
	"yly.elderlyInfo.housingInfo":"住房信息",
	"yly.elderlyInfo.medicalExpPaymentWay":"医疗支付方式",
	"yly.elderlyInfo.monthlyIncome":"月收入",
	"yly.elderlyInfo.sourceOfIncome":"收入来源",
	"yly.elderlyInfo.elderlyConsigner":"委托人",
	"yly.elderlyInfo.elderlyConsigner.consignerPhoneNumber":"委托人电话",
	"yly.elderlyInfo.elderlyFamilyMembers":"家庭成员",
	 "yly.elderlyInfo.familyMember.memberName":"成员名称",
	"yly.elderlyInfo.familyMember.PhoneNumber":"成员电话",
	//床位管理
	"yly.bulding.add":"添加楼宇",
	"yly.bulding.edit":"楼宇编辑",
	"yly.bulding.list":"楼宇列表",
	"yly.bulding.buildingName":"楼宇名称",
	"yly.bulding.description":"描述",
	"yly.room.add":"房间添加",
	"yly.room.edit":"房间编辑",
	"yly.room.list":"房间列表",
	"yly.room.roomName":"房间名称",
	"yly.room.roomNumber":"房间编号",
	"yly.room.floor":"房间所在楼层",
	"yly.room.roomType":"房间类型",
	"yly.room.roomStatus":"房间状态",
	"yly.room.building":"所属楼宇",
	"yly.room.description":"房间描述",
	"yly.bed.add":"床位添加",
	"yly.bed.edit":"床位编辑",
	"yly.bed.list":"床位列表",
	"yly.bed.bedNumber":"床位号",
	"yly.bed.status":"床位状态",
	"yly.bed.description":"描述",
	"yly.bed.room":"所在房间",
	"yly.common.unappropriated":"未占用",
	"yly.common.occupied":"已占用",
	"yly.bed.usageState":"是否被占用",
	//黑名单
	"yly.blacklist.record":"黑名单",
	"yly.blacklist.name":"黑名单老人名字",
	"yly.blacklist.geracomium":"所属养老院",
	"yly.blacklist.casue":"加入黑名单原因",
	"yly.blacklist.add":"加入黑名单",
	
	//换房
	"yly.residential.changeRoom.elderly":"请选择换房老人",
		
	//老人管理
	"yly.elderlyInfo.common.operator":"记录人",
	"yly.elderlyInfo.event.eventDate":"事件发生时间",
	"yly.elderlyInfo.event.content":"事件内容",
	"yly.elderlyInfo.event.list":"事件列表",
    "yly.elderly.event.add":"添加事件",
    "yly.elderly.event.edit":"编辑事件",
    "yly.elderlyInfo.stuffDeposit.list":"物品寄存列表",
    "yly.elderly.stuffDeposit.add":"添加物品寄存",
    "yly.elderly.stuffDeposit.edit":"编辑物品寄存",
    //老人相册
    "yly.elderly.Photo.Album":"相册名称",
    "yly.elderly.Photo.Album.view":"浏览图片",
    "yly.elderly.Photo.Album.add":"添加相册照片",
    "yly.elderly.Photo.Album.edit":"编辑相册",
    "yly.elderly.Photo.Album.confirm_delete_album_and_allPhotos":"确定删除相册以及相册下的所有照片吗？",
    "yly.elderly.Photo.Album.edit_success":"相册编辑成功",
    "yly.elderly.Photo.Album.click_choose_photo":"点击选择图片",
    "yly.elderly.Photo.Album.upload":"上传照片",
    "yly.elderly.Photo.Album.setAlbum":"设置封面",
    "yly.elderly.Photo.Album.chooseAlbum":"选择相册",
    "yly.elderly.Photo.Album.upload_success":"照片上传成功",
    "yly.elderly.Photo.Album.search":"相册查询",
    "yly.elderly.Photo.Album.albumCover":"封面",
    "yly.elderly.Photo.Album.albumName":"相册名",
	//物品寄存
    "yly.elderlyInfo.stuffDeposit.name":"物品名称",	
    "yly.elderlyInfo.stuffDeposit.count":"数量",
    "yly.elderlyInfo.stuffDeposit.remark":"物品备注",
    "yly.elderlyInfo.stuffDeposit.stuffNumer":"物品编号",
    "yly.elderlyInfo.stuffDeposit.status":"寄存状态",
    "yly.elderlyInfo.stuffDeposit.inputDate":"寄存时间",
    "yly.elderlyInfo.stuffDeposit.takeAwayDate":"取出时间",	
    "yly.elderlyInfo.stuffDeposit.elderlyName":"所属老人",
    "yly.elderlyInfo.stuffDeposit.putin":"存入",
    "yly.elderlyInfo.stuffDeposit.takeaway":"取走",
    //入院评估
    "yly.elderly.evaluating.info_no_enough":"信息不够信息提供有误或者不够完善！请核查...",
    "yly.elderly.evaluating.section_level_error":"模块等级计算有误！",
    "yly.elderly.evaluating.form_level_error":"评估表等级计算有误！",
    "yly.elderly.evaluating.dialog_title.select_form":"选择评估表",
    "yly.elderly.evaluating.dialog_title.add_custom_form":"添加自定义入院评估",
    "yly.elderly.evaluating.dialog_title.add_evaluating":"添加入院评估",
    "yly.elderly.evaluating.dialog_title.edit_evaluating":"编辑入院评估记录",
    "yly.elderly.evaluating.dialog_title.evaluating_list":"入院评估记录列表",
    "yly.elderly.evaluating.dialog_title.custom_form":"自定义评估表",
    "yly.elderly.evaluating.dialog_title.edit_option":"编辑选项",
    "yly.elderly.evaluating.dialog_title.edit_section":"编辑模块",
    "yly.elderly.evaluating.dialog_choose_existing_item":"选择已有题目",
    "yly.elderly.evaluating.dialog_customItem":"自定义题目",
    "yly.elderly.evaluating.dialog_customSection":"自定义模块",
    "yly.elderly.evaluating.elderlyInfoName":"被评估老人",
    "yly.elderly.evaluating.operator":"评估操作人",
    "yly.elderly.evaluating.evaluatingReason":"评估原因",
    "yly.elderly.evaluating.evaluatingResult":"评估结果",
    "yly.elderly.evaluating.evaluatingFormName":"评估表名及编号",
    "yly.elderly.evaluating.evaluatingDate":"评估基准时间",
    "yly.elderly.evaluating.CHECKIN_EVALUATING":"接受服务前初评",
    "yly.elderly.evaluating.ROUTINE_EVALUATING":"接受服务后的常规评估",
    "yly.elderly.evaluating.IMMEDIATE_EVALUATING":"状况发生变化后的即时评估",
    "yly.elderly.evaluating.QUESTION_EVALUATING":"因评估结果有疑问进行的复评",
    "yly.elderly.evaluating.beginScore_lower_equal_endScore":"起始分数应该小于等于终止分数!",
    "yly.elderly.evaluating.nearScore_keyin_error":"相邻等级的终止分数和起始分数输入有误,否者没法根据具体分数明确的划分等级分数区间!",
    "yly.elderly.evaluating.customForm_create_success":"自定义评估表: {0} 创建成功!",
    "yly.elderly.evaluating.please_config_evaluating_level":"请先在系统配置的数据字典中配置评估等级!",
    "yly.elderly.evaluating.please_add_section":"请添加模块!",
    "yly.elderly.evaluating.please_keyin_form_name":"请输入表名称!",
    "yly.elderly.evaluating.please_keyin_evaluating_rule":"请输入评估等级评分规则!",
    "yly.elderly.evaluating.item_name":"题目名称",
    "yly.elderly.evaluating.items_base_search":"题库查询",
    "yly.elderly.evaluating.confirm_theOption":"确定删除此选项吗?",
    "yly.elderly.evaluating.confirm_theItem":"确定删除此题目吗?",
    "yly.elderly.evaluating.missing_info":"还有未填字段!",
    "yly.elderly.evaluating.section_contain_theItem":"未分配的模块已经包含此题目，请另外添加其他题目!",
    "yly.elderly.evaluating.section_existing":"{0} 模块已经添加,不能重复添加!",
    "yly.elderly.evaluating.evaluating_section":"评估模块",
    "yly.elderly.evaluating.item_cannot_delete":"题目：{0} 已经被其他模块使用，不能被删除！！",
    "yly.elderly.evaluating.delete_item":"删除题目",
    "yly.elderly.evaluating.add_item":"添加题目",
    "yly.elderly.evaluating.option_name":"选项名称",
    "yly.elderly.evaluating.score":"得分",
    
    //维修人员
    "yly.repairRecord.add":"添加维修记录",
	"yly.repairRecord.record":"维修记录",
	"yly.repairRecord.repairContent":"维修内容",
	"yly.repairRecord.repairPlace":"维修地点",
	"yly.repairRecord.reportOperator":"报修人",
	"yly.repairRecord.repairOperator":"维修人员",
	
	//水电用量记录
	"yly.waterElectricityRecord.add":"水电用量记录添加",
	"yly.waterElectricityRecord.record":"水电用量列表",
	"yly.waterElectricityRecord.waterActual":"用水计费吨数",
	"yly.waterElectricityRecord.electricityActual":"用电计费度数",
	"yly.waterElectricityRecord.operator":"抄表人",
	
	//药品管理
	"yly.drugsInfo.list":"药品列表",
	"yly.drugsInfo.add":"药品添加",
	"yly.drugsInfo.name":"药品名称",
	"yly.drugsInfo.alias":"别名",
	"yly.drugsInfo.drugCategory":"药品分类",
	
	//捐赠管理
	"yly.donateRecord.list":"捐赠记录",
	"yly.donateRecord.add":"添加捐赠记录",
	"yly.donateRecord.donatorName":"捐赠记录",
	"yly.donateRecord.donatorPhone":"捐赠人电话",
	"yly.donateRecord.donateTime":"捐赠时间",
	"yly.donateDetail.donateAmount":"捐赠数",
	"yly.donateDetail.donateType":"捐赠类型",
	"yly.donateDetail.donateType.money":"钱",
	"yly.donateDetail.donateType.item":"物",
	"yly.donateDetail.donateItemType":"捐赠物品类型",
	"yly.donateDetail.add":"添加捐赠详情",
	//固定资产
	"yly.fixedAssets.list":"固定资产列表",
	"yly.fixedAssets.assetNo":"资产编号",
	"yly.fixedAssets.assetName":"资产名称",
	"yly.fixedAssets.department":"存放部门",
	"yly.fixedAssets.assetCount":"资产数量",
	"yly.fixedAssets.assetTime":"录入时间",
	"yly.fixedAssets.add":"固定资产添加",
	//租户用户
	"yly.tenantUser.search":"用户查询",
	"yly.tenantUser.list":"用户列表",
	"yly.tenantUser.realName":"姓名",
	"yly.tenantUser.gender":"性别",
	"yly.tenantUser.age":"年龄",
	"yly.tenantUser.staffID":"员工编号",
	"yly.tenantUser.staffStatus":"员工状态",
	"yly.tenantUser.staffStatus.inService":"在职",
	"yly.tenantUser.staffStatus.outService":"离职",
	"yly.tenantUser.department":"所在部门",
	"yly.tenantUser.position":"担任职务",
	"yly.tenantUser.hireDate":"入职时间",
	
	//department
	"yly.department.name":"部门名称",
	"yly.department.grade":"部门层级",
	"yly.department.parent":"上级部门",
	"yly.department.add":"添加部门",
	
	//position
	"yly.position.add":"添加职位",
	"yly.position.name":"职位名称",
	"yly.position.department":"隶属部门",

	//权限管理
	"yly.role.record":"角色管理",
	"yly.role.name":"角色名称",
	"yly.role.description":"描述",
	"yly.role.add":"添加角色",
	"yly.role.auth":"授权",
	"yly.role.auth.manange":"权限分配",
	"yly.role.auth.name":"菜单名称",
	"yly.role.auth.status":"权限状态",
	"yly.drugsInfo.doseFrequency.Qd":"一天一次(Qd)",
	"yly.drugsInfo.doseFrequency.Bid":"一天两次(Bid)",
	"yly.drugsInfo.doseFrequency.Tid":"一天三次(Tid)",
	"yly.drugsInfo.doseFrequency.Qid":"一天四次(Qid)",
	"yly.drugsInfo.doseFrequency.Q2h":"两小时一次(Q2h)",
	"yly.drugsInfo.doseFrequency.Q4h":"四小时一次(Q4h)",
	//病历管理
	"yly.medicalRecord.list":"病历列表",
	"yly.medicalRecord.add":"添加病历",
	"yly.prescriptionDrugsItem.delete.confirm":"删除后不可恢复，确认？",
	//通知公告
	"yly.notification.operator":"发布人",
	"yly.notification.publishTime":"发布时间",
	"yly.notification.list":"通知列表",
	"yly.notification.add":"添加通知公告",
	
	"yly.industryInformation.list":"业内咨询列表",
	"yly.industryInformation.add":"添加资讯",
	// 租户用户
	"yly.tenantAccount.add":"添加用户",
	"yly.tenantAccount.userName":"用户名",
	"yly.tenantAccount.realName":"真实姓名",
	"yly.tenantAccount.isSystem":"是否内置",
	"yly.tenantAccount.accoutStatus":"账号状态",
	"yly.tenantAccount.loginDate":"最后登录时间",
	"yly.tenantAccount.loginIp":"最后登录IP",
	"yly.tenantAccount.active":"账号正常",
	"yly.tenantAccount.list":"用户列表",
	"yly.tenantAccount.locked":"账号锁定",
	//体检项配置
	"yly.physicalExaminationItemConfig.list":"体检项列表",
	"yly.physicalExaminationItemConfig.isEnable":"是否启用",
	"yly.physicalExaminationItemConfig.name":"体检项名称",
	"yly.physicalExaminationItemConfig.search":"体检配置项搜索",
	"yly.physicalExamination.list":"体检记录列表",
	"yly.physicalExamination.add":"添加体检记录",
	"yly.physicalExamination.operator":"录入人",
	
	//数据字典
	"yly.systemConfig.list":"数据字典",
	"yly.systemConfig.configValue":"配置项值",
	"yly.systemConfig.isEnabled":"是否启用",
	"yly.systemConfig.add":"添数据字典",
	"yly.systemConfig.edit":"编辑数据字典",
	
	
	//排班
	"yly.nurseDutyType.list":"班次类型列表",
	"yly.nurseDutyType.add":"添加班次",
	"yly.nurseDutyType.dutyStartTime":"开始时间",
	"yly.nurseDutyType.dutyEndTime":"结束时间",
	"yly.nurseDutyType.dutyName":"班次名称",
	"yly.nurseDutyType.order":"排序",
	"yly.nurseDutyType.remark":"备注",
	//护理计划
	"yly.nursePlan.list":"护理计划列表",
	"yly.nursePlan.add":"添加护理计划",
	"yly.nursePlan.edit":"编辑护理计划",
	"yly.nursePlan.planStartDate":"开始时间",
	"yly.nursePlan.planEndDate":"结束时间",
	"yly.nursePlan.planName":"计划名称",
	"yly.nursePlan.planContent":"计划内容",
	"yly.nursePlan.remark":"备注",
	
	//个性化护理
	"yly.personalizedNurse.list":"个性化护理列表",
	"yly.personalizedNurse.add":"添加个性化护理",
	"yly.personalizedNurse.edit":"个性化护理编辑",
	"yly.personalizedNurse.elderlyInfo":"老人",
	"yly.personalizedNurse.applyTime":"登记时间",
	"yly.personalizedNurse.sumCount":"服务总次数",
	"yly.personalizedNurse.usedCount":"已使用次数",
	"yly.personalizedNurse.nurseContent":"护理内容",
	"yly.personalizedNurse.operator":"经办人",
	"yly.personalizedNurse.servicePrice":"服务单价",
    "yly.personalizedNurse.remark":"备注",
    
    //护理员安排
    "yly.nurseArrangement.list":"护理员安排列表",
    "yly.nurseArrangement.nurseAssistant":"护理员姓名",
    "yly.nurseArrangement.nurseStartDate":"护理开始日期",
    "yly.nurseArrangement.nurseEndDate":"护理结束日期",
    "yly.nurseArrangement.nurseName":"护理名称",
    "yly.nurseArrangement.nursingLevel":"护理级别",
    "yly.nurseArrangement.addNurse":"添加护理员安排",
    "yly.nurseArrangement.addNurseRecord":"添加护理员安排明细",
    "yly.nurseArrangementRecord.list":"护理员护理明细",
    "yly.nurseArrangement.nurseServiceTime":"护理执行时间",
    "yly.nurseArrangement.nurseAssistant.staffID":"员工号",
    "yly.nurseArrangement.nurseAssistant.staffStatus":"员工状态",
    "yly.nurseArrangement.search":"护理员安排查询",
    //护理变更
    "yly.nurseChange.addNurseChange":"添加护理变更",
    "yly.nurseChange.list":"护理变更记录列表",
    "yly.nurseChange.oldNurseLevel":"变更前护理级别",
    "yly.nurseChange.newNurseLevel":"变更后护理级别",
    "yly.nurseChange.changeDate":"变更日期",
    "yly.nurseChange.nurseChangeStatus":"变更记录的状态",
    
    //nurseSchedule
    "yly.nurseSchedule.add":"添加值班安排",
    "yly.nurseSchedule.list":"值班安排列表",
    "yly.nurseSchedule.edit":"编辑值班安排",
    "yly.nurseSchedule.dutyStartTime":"排班开始时间",
    "yly.nurseSchedule.dutyEndTime":"排班结束时间",
    "yly.nurseSchedule.dutyType":"值班类型",
    "yly.nurseSchedule.dutyStaff":"值班人姓名",
    
    "yly.personalizedNurse.nurseLevel":"护理级别",
    "yly.personalizedNurse.personalized":"服务项目",
    //personalizedRecord
    "yly.personalizedRecord.serviceTime":"服务时间",
    "yly.personalizedRecord.elderlyInfo":"老人",
    "yly.personalizedRecord.operator":"服务护工",
    "yly.personalizedRecord.personalizedNurse":"服务项目",
    "yly.personalizedRecord.chargeStatus":"计费状态",
    "yly.personalizedRecord.nurseContent":"护理内容",
    "yly.personalizedRecord.remark":"备注",
    "yly.personalizedRecord.list":"个性化护理详细记录列表",
    "yly.personalizedRecord.add":"添加个性化护理详情",
    
    "yly.residential.changeRoom.action":"换房"
};
//多语言
function message(code) {
	if (code != null) {
		var content = messages[code] != null ? messages[code] : code;
		if (arguments.length == 1) {
			return content;
		} else {
			if ($.isArray(arguments[1])) {
				$.each(arguments[1], function(i, n) {
					content = content.replace(
							new RegExp("\\{" + i + "\\}", "g"), n);
				});
				return content;
			} else {
				$.each(Array.prototype.slice.apply(arguments).slice(1),
						function(i, n) {
							content = content.replace(new RegExp("\\{" + i
									+ "\\}", "g"), n);
						});
				return content;
			}
		}
	}
}
